server:
  port: 8000
  servlet:
    context-path: /permission

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zy-permission
    username: root
    password: 12345678
  jpa:
    show-sql: true



